//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Icons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Icons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Icons", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-chart-curve.
        /// </summary>
        internal static string analytics {
            get {
                return ResourceManager.GetString("analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-multiple-credit-cards.
        /// </summary>
        internal static string analytics_orders {
            get {
                return ResourceManager.GetString("analytics-orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-tag.
        /// </summary>
        internal static string analytics_products {
            get {
                return ResourceManager.GetString("analytics-products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-book-alt-2.
        /// </summary>
        internal static string catalog {
            get {
                return ResourceManager.GetString("catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-tag.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-speed-gauge.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-pie-chart.
        /// </summary>
        internal static string marketing {
            get {
                return ResourceManager.GetString("marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-newspaper.
        /// </summary>
        internal static string marketing_campaign {
            get {
                return ResourceManager.GetString("marketing-campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-badge-add .
        /// </summary>
        internal static string marketing_campaign_active {
            get {
                return ResourceManager.GetString("marketing-campaign-active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-badge-remove.
        /// </summary>
        internal static string marketing_campaign_inactive {
            get {
                return ResourceManager.GetString("marketing-campaign-inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-wand.
        /// </summary>
        internal static string option_create {
            get {
                return ResourceManager.GetString("option-create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-delete-key.
        /// </summary>
        internal static string option_delete {
            get {
                return ResourceManager.GetString("option-delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-download-alt.
        /// </summary>
        internal static string option_export {
            get {
                return ResourceManager.GetString("option-export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-axis-rotation.
        /// </summary>
        internal static string option_refresh {
            get {
                return ResourceManager.GetString("option-refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-ordered-list.
        /// </summary>
        internal static string option_sort {
            get {
                return ResourceManager.GetString("option-sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-multiple-credit-cards.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-credit-card-alt.
        /// </summary>
        internal static string orders_order {
            get {
                return ResourceManager.GetString("orders-order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-multiple-credit-cards.
        /// </summary>
        internal static string orders_ordergroup {
            get {
                return ResourceManager.GetString("orders-ordergroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-search.
        /// </summary>
        internal static string orders_search {
            get {
                return ResourceManager.GetString("orders-search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-t-shirt.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-search.
        /// </summary>
        internal static string products_search {
            get {
                return ResourceManager.GetString("products-search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-app.
        /// </summary>
        internal static string settings_apps {
            get {
                return ResourceManager.GetString("settings-apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-book-alt-2.
        /// </summary>
        internal static string settings_catalog {
            get {
                return ResourceManager.GetString("settings-catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-coin.
        /// </summary>
        internal static string settings_catalog_pricegroup {
            get {
                return ResourceManager.GetString("settings-catalog-pricegroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-coins-alt.
        /// </summary>
        internal static string settings_catalog_pricegroups {
            get {
                return ResourceManager.GetString("settings-catalog-pricegroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-molecular-network.
        /// </summary>
        internal static string settings_catalog_product_relation {
            get {
                return ResourceManager.GetString("settings-catalog-product-relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-molecular.
        /// </summary>
        internal static string settings_catalog_product_relations {
            get {
                return ResourceManager.GetString("settings-catalog-product-relations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_datatype_bool {
            get {
                return ResourceManager.GetString("settings-datatype-bool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_datatype_content {
            get {
                return ResourceManager.GetString("settings-datatype-content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_datatype_enum {
            get {
                return ResourceManager.GetString("settings-datatype-enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_datatype_media {
            get {
                return ResourceManager.GetString("settings-datatype-media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_datatype_number {
            get {
                return ResourceManager.GetString("settings-datatype-number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_datatype_text {
            get {
                return ResourceManager.GetString("settings-datatype-text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_definitions {
            get {
                return ResourceManager.GetString("settings-definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-mindmap.
        /// </summary>
        internal static string settings_definitions_data_type {
            get {
                return ResourceManager.GetString("settings-definitions-data-type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-mindmap.
        /// </summary>
        internal static string settings_definitions_data_types {
            get {
                return ResourceManager.GetString("settings-definitions-data-types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_definitions_dynamic_definition_item {
            get {
                return ResourceManager.GetString("settings-definitions-dynamic-definition-item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_definitions_dynamic_definition_items {
            get {
                return ResourceManager.GetString("settings-definitions-dynamic-definition-items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-tag.
        /// </summary>
        internal static string settings_definitions_product_definition {
            get {
                return ResourceManager.GetString("settings-definitions-product-definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-tag.
        /// </summary>
        internal static string settings_definitions_product_definitions {
            get {
                return ResourceManager.GetString("settings-definitions-product-definitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-autofill.
        /// </summary>
        internal static string settings_dynamic_definition {
            get {
                return ResourceManager.GetString("settings-dynamic-definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-message.
        /// </summary>
        internal static string settings_email {
            get {
                return ResourceManager.GetString("settings-email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-message.
        /// </summary>
        internal static string settings_email_profile {
            get {
                return ResourceManager.GetString("settings-email-profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-message.
        /// </summary>
        internal static string settings_email_profiles {
            get {
                return ResourceManager.GetString("settings-email-profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-message.
        /// </summary>
        internal static string settings_email_profile_item {
            get {
                return ResourceManager.GetString("settings-email-profile-item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-message.
        /// </summary>
        internal static string settings_email_type {
            get {
                return ResourceManager.GetString("settings-email-type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-message.
        /// </summary>
        internal static string settings_email_types {
            get {
                return ResourceManager.GetString("settings-email-types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-box.
        /// </summary>
        internal static string settings_installed_apps {
            get {
                return ResourceManager.GetString("settings-installed-apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-cloud-upload.
        /// </summary>
        internal static string settings_install_app {
            get {
                return ResourceManager.GetString("settings-install-app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-multiple-credit-cards.
        /// </summary>
        internal static string settings_orders {
            get {
                return ResourceManager.GetString("settings-orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-globe-europe---africa.
        /// </summary>
        internal static string settings_orders_countries {
            get {
                return ResourceManager.GetString("settings-orders-countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-globe-europe---africa.
        /// </summary>
        internal static string settings_orders_country {
            get {
                return ResourceManager.GetString("settings-orders-country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-bill.
        /// </summary>
        internal static string settings_orders_currencies {
            get {
                return ResourceManager.GetString("settings-orders-currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-bill.
        /// </summary>
        internal static string settings_orders_currency {
            get {
                return ResourceManager.GetString("settings-orders-currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-binarycode.
        /// </summary>
        internal static string settings_orders_order_number {
            get {
                return ResourceManager.GetString("settings-orders-order-number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-binarycode.
        /// </summary>
        internal static string settings_orders_order_numbers {
            get {
                return ResourceManager.GetString("settings-orders-order-numbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-credit-card.
        /// </summary>
        internal static string settings_orders_payment_method {
            get {
                return ResourceManager.GetString("settings-orders-payment-method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-credit-card.
        /// </summary>
        internal static string settings_orders_payment_methods {
            get {
                return ResourceManager.GetString("settings-orders-payment-methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-truck.
        /// </summary>
        internal static string settings_orders_shipping_method {
            get {
                return ResourceManager.GetString("settings-orders-shipping-method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-truck.
        /// </summary>
        internal static string settings_orders_shipping_methods {
            get {
                return ResourceManager.GetString("settings-orders-shipping-methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-search.
        /// </summary>
        internal static string settings_search {
            get {
                return ResourceManager.GetString("settings-search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-lock.
        /// </summary>
        internal static string settings_security {
            get {
                return ResourceManager.GetString("settings-security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-users-alt.
        /// </summary>
        internal static string settings_security_group {
            get {
                return ResourceManager.GetString("settings-security-group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-users-alt.
        /// </summary>
        internal static string settings_security_groups {
            get {
                return ResourceManager.GetString("settings-security-groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-user-female.
        /// </summary>
        internal static string settings_security_user {
            get {
                return ResourceManager.GetString("settings-security-user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-user-female.
        /// </summary>
        internal static string settings_security_users {
            get {
                return ResourceManager.GetString("settings-security-users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-cash-register.
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon icon-store.
        /// </summary>
        internal static string stores {
            get {
                return ResourceManager.GetString("stores", resourceCulture);
            }
        }
    }
}
